"""Applicability, gate evaluation and persistence of the results.

The pure part (:func:`evaluate_unit`) turns a :class:`DeclarationSet`
into :class:`Element` objects with their applicable rules and
:class:`GateResult` verdicts. The impure part (:func:`apply_to_folder`)
writes those onto disk in the shape later tickets build on: element
``.gen.yaml`` files, the checkpoint ledger, and finding files.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any

import yaml

from model_wtf.compliance.declarations.ids import id_from_path
from model_wtf.compliance.declarations.loader import Kind
from model_wtf.compliance.declarations.schemas import (
    Checkpoint,
    CheckpointStatus,
    Evaluated,
    Finding,
    Generated,
    Ledger,
)
from model_wtf.compliance.engine.helpers import build_namespace
from model_wtf.compliance.engine.safe_eval import ConditionError, evaluate
from model_wtf.knowledge.schemas import RuleKind

if TYPE_CHECKING:
    from pathlib import Path

    from pydantic import BaseModel

    from model_wtf.compliance.declarations.loader import DeclarationSet, Declared
    from model_wtf.knowledge.loader import Knowledge
    from model_wtf.knowledge.schemas import Rule

ELEMENT_KIND_OF: dict[Kind, str] = {
    Kind.DATA_OBJECT: "data_object",
    Kind.ACTIVITY: "activity",
    Kind.RECIPIENT: "recipient",
}
"""Declaration kinds that are elements today, and their rule-facing kind."""

ENGINE_MODEL = "engine"
GEN_HEADER = "# GENERATED by model-wtf -- do not edit; the ledger is the .yaml twin\n"


class EngineError(Exception):
    """A rule condition could not be evaluated: a Knowledge bug, exit 4."""


@dataclass(slots=True)
class Element:
    """Something rules can apply to, with its declaration and facts.

    Attribute access falls through to ``model`` so that conditions read
    naturally (``recipient.kind``) while helpers still receive the whole
    element (to reach the ``.gen`` facts). The element's own attributes are
    named so as not to shadow model fields (``element_kind``, not ``kind``).
    """

    id: str
    element_kind: str
    stacks: frozenset[str]
    model: BaseModel | None
    gen: Generated | None
    source: Declared[Any]
    applicable: list[Rule] = field(default_factory=list)
    not_applicable: dict[str, str] = field(default_factory=dict)

    def __getattr__(self, name: str) -> Any:
        if name.startswith("_") or self.model is None:
            raise AttributeError(name)
        return getattr(self.model, name)

    @property
    def stable_id(self) -> str:
        """Id used in checkpoint keys (``RULE@<stable_id>``)."""
        return f"{self.element_kind}:{self.id}"


@dataclass(frozen=True, slots=True)
class GateResult:
    """The verdict of one gate on one element."""

    element: Element
    rule: Rule
    passed: bool

    @property
    def status(self) -> CheckpointStatus:
        """``ok`` or ``not_ok``."""
        return CheckpointStatus.OK if self.passed else CheckpointStatus.NOT_OK

    @property
    def checkpoint(self) -> str:
        """``RULE@element`` key."""
        return f"{self.rule.id}@{self.element.stable_id}"


@dataclass(slots=True)
class UnitEvaluation:
    """Everything the engine computed for one unit."""

    elements: list[Element]
    gates: list[GateResult]

    @property
    def failures(self) -> list[GateResult]:
        """Gates that did not pass."""
        return [g for g in self.gates if not g.passed]


def evaluate_unit(
    ds: DeclarationSet, knowledge: Knowledge, framework: str | None = None
) -> UnitEvaluation:
    """Compute elements, applicability and gate verdicts (no I/O).

    Parameters
    ----------
    ds
        The unit's declarations (already integrity-checked).
    knowledge
        The loaded Knowledge.
    framework
        Restrict to rules tagged with this framework (``None``/``"all"``
        for everything).

    Raises
    ------
    EngineError
        When a gate condition cannot be evaluated.
    """
    candidates = knowledge.by_framework(framework)
    elements = [
        _element(kind, declared)
        for kind in ELEMENT_KIND_OF
        for declared in ds.unit.get(kind).values()
    ]
    gates: list[GateResult] = []
    for element in elements:
        for rule in candidates:
            if rule.applies_to.matches(element.element_kind, element.stacks):
                element.applicable.append(rule)
            else:
                element.not_applicable[rule.id] = _why_not(rule, element)
        for rule in element.applicable:
            if rule.kind is RuleKind.GATE and element.model is not None:
                gates.append(_run_gate(element, rule, ds, knowledge))
    return UnitEvaluation(elements=elements, gates=gates)


def _element(kind: Kind, declared: Declared[Any]) -> Element:
    return Element(
        id=declared.id,
        element_kind=ELEMENT_KIND_OF[kind],
        stacks=frozenset(),
        model=declared.model,
        gen=declared.gen,
        source=declared,
    )


def _why_not(rule: Rule, element: Element) -> str:
    target = rule.applies_to
    if target.kind.value != element.element_kind:
        return f"applies to {target.kind.value}, element is {element.element_kind}"
    return f"applies to stacks {', '.join(target.stack)}"


def _run_gate(
    element: Element, rule: Rule, ds: DeclarationSet, knowledge: Knowledge
) -> GateResult:
    assert rule.condition is not None  # noqa: S101 - enforced by the Rule schema
    try:
        passed = evaluate(rule.condition, build_namespace(element, ds, knowledge))
    except ConditionError as exc:
        msg = f"{rule.id} on {element.stable_id}: {exc}"
        raise EngineError(msg) from exc
    return GateResult(element=element, rule=rule, passed=passed)


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Written:
    """What :func:`apply_to_folder` changed on disk."""

    gen_files: tuple[Path, ...]
    ledgers: tuple[Path, ...]
    findings_created: tuple[Path, ...]
    findings_deleted: tuple[Path, ...]


def apply_to_folder(
    folder: Path,
    evaluation: UnitEvaluation,
    *,
    sha: str = "unknown",
    root: Path | None = None,
) -> Written:
    """Write applicability, ledger verdicts and findings under ``folder``.

    Only gate checkpoints are touched: entries the agent wrote for verify
    rules are preserved verbatim, and applicable verify rules that have no
    entry yet are seeded as ``unknown`` so the agent knows what to do.
    Findings for gates are created on ``not_ok`` and deleted on ``ok``;
    numbering is a simple ``.seq`` counter (the full reconcile with
    collision handling belongs to the ledger ticket). An unchanged verdict
    keeps its previous ``evaluated`` block so re-running ``check`` does not
    churn timestamps.

    ``root`` (the repo root) makes ``depends_on`` / ``provenance`` paths
    repo-relative; it defaults to the folder's parent.
    """
    root = root or folder.parent
    elements_dir = folder / "elements"
    findings_dir = folder / "findings"
    now = datetime.now(tz=UTC)

    gen_files: list[Path] = []
    ledgers: list[Path] = []
    created: list[Path] = []
    deleted: list[Path] = []

    gates_by_element: dict[str, list[GateResult]] = {}
    for gate in evaluation.gates:
        gates_by_element.setdefault(gate.element.id, []).append(gate)

    for element in evaluation.elements:
        elements_dir.mkdir(parents=True, exist_ok=True)
        file_id = _file_id(element)
        gen_path = elements_dir / f"{file_id}.gen.yaml"
        _write_gen(gen_path, element)
        gen_files.append(gen_path)

        ledger_path = elements_dir / f"{file_id}.yaml"
        ledger = _read_ledger(ledger_path)
        for rule in element.applicable:
            if rule.kind is RuleKind.VERIFY and rule.id not in ledger:
                ledger[rule.id] = Checkpoint(status=CheckpointStatus.UNKNOWN)
        for gate in gates_by_element.get(element.id, []):
            outcome = _apply_gate(ledger, gate, findings_dir, root, sha, now)
            created.extend(outcome.created)
            deleted.extend(outcome.deleted)
        _write_yaml(
            ledger_path,
            {
                rule_id: cp.model_dump(
                    mode="json", exclude_none=True, exclude_defaults=True
                )
                for rule_id, cp in ledger.items()
            },
        )
        ledgers.append(ledger_path)

    return Written(tuple(gen_files), tuple(ledgers), tuple(created), tuple(deleted))


@dataclass(slots=True)
class _GateOutcome:
    created: list[Path] = field(default_factory=list)
    deleted: list[Path] = field(default_factory=list)


def _write_gen(path: Path, element: Element) -> None:
    """The element's ``.gen.yaml``: kind, stable id, applicability."""
    _write_yaml(
        path,
        {
            "by": "extractor",
            "kind": element.element_kind,
            "stable_id": element.stable_id,
            "applicable_rules": [r.id for r in element.applicable],
            "not_applicable": dict(sorted(element.not_applicable.items())),
        },
        header=GEN_HEADER,
    )


def _apply_gate(
    ledger: dict[str, Checkpoint],
    gate: GateResult,
    findings_dir: Path,
    root: Path,
    sha: str,
    now: datetime,
) -> _GateOutcome:
    """Update one ledger entry and its finding for a gate verdict.

    A checkpoint a human marked ``accepted`` is left alone while the gate
    still fails: their entry and finding are the record of that decision.
    """
    outcome = _GateOutcome()
    previous = ledger.get(gate.rule.id)
    finding_id = previous.finding if previous else None
    evaluated = Evaluated(sha=sha, model=ENGINE_MODEL, at=now, by="engine")
    if (
        previous is not None
        and previous.status is CheckpointStatus.ACCEPTED
        and not gate.passed
    ):
        return outcome

    if previous is not None and previous.status is gate.status:
        # Same verdict as last time: keep the provenance, only refresh the
        # finding text (the rule wording may have changed).
        if not gate.passed and finding_id:
            _write_finding(
                findings_dir / f"{finding_id}.yaml", gate, previous.evaluated, root
            )
        return outcome

    if gate.passed:
        if finding_id and (findings_dir / f"{finding_id}.yaml").exists():
            (findings_dir / f"{finding_id}.yaml").unlink()
            outcome.deleted.append(findings_dir / f"{finding_id}.yaml")
        finding_id = None
    else:
        findings_dir.mkdir(parents=True, exist_ok=True)
        if not finding_id or not (findings_dir / f"{finding_id}.yaml").exists():
            finding_id = _allocate(findings_dir)
            outcome.created.append(findings_dir / f"{finding_id}.yaml")
        _write_finding(findings_dir / f"{finding_id}.yaml", gate, evaluated, root)

    ledger[gate.rule.id] = Checkpoint(
        status=gate.status,
        evaluated=evaluated,
        depends_on=[_relative(gate.element.source.path, root)],
        evidence=(
            f"gate condition of {gate.rule.id} v{gate.rule.version} holds"
            if gate.passed
            else None
        ),
        finding=finding_id,
    )
    return outcome


def _file_id(element: Element) -> str:
    """``<kind>.<id>``: keeps registry elements apart from surface ones."""
    return f"{element.element_kind}.{element.id}"


def _relative(path: Path, root: Path) -> str:
    """``path`` relative to the repo root (absolute if outside it)."""
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path)


def _read_ledger(path: Path) -> dict[str, Checkpoint]:
    if not path.is_file():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return Ledger.model_validate(data).checkpoints


def _allocate(findings_dir: Path) -> str:
    """Next ``F-NNNN`` from ``.seq`` (numbers are never reused)."""
    seq = findings_dir / ".seq"
    last = int(seq.read_text().strip() or 0) if seq.is_file() else 0
    existing = [
        int(id_from_path(p.name)[2:])
        for p in findings_dir.glob("F-*.yaml")
        if id_from_path(p.name)[2:].isdigit()
    ]
    number = max([last, *existing]) + 1
    seq.write_text(f"{number}\n", encoding="utf-8")
    return f"F-{number:04d}"


def _write_finding(
    path: Path, gate: GateResult, evaluated: Evaluated | None, root: Path
) -> None:
    """Render a gate failure as a finding file, in the agent's format."""
    rule = gate.rule
    finding = Finding(
        checkpoint=gate.checkpoint,
        severity=rule.severity.value,
        summary=f"{rule.title} ({gate.element.stable_id})",
        detail=(
            f"{rule.description.strip()}\n\nGate condition failed: "
            f"{rule.condition.strip() if rule.condition else ''}"
        ),
        remediation=rule.mitigation.strip(),
        references=list(rule.references),
        provenance=[_relative(gate.element.source.path, root)],
        evaluated=evaluated
        or Evaluated(
            sha="unknown", model=ENGINE_MODEL, at=datetime.now(tz=UTC), by="engine"
        ),
    )
    _write_yaml(path, finding.model_dump(mode="json", exclude_none=True))


def _write_yaml(path: Path, data: dict[str, Any], header: str = "") -> None:
    """Dump ``data`` deterministically (stable key order, block style)."""
    text = yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=88)
    content = header + text
    if not path.is_file() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")
