"""Clustering entrypoints/tasks into `processing/*.gen.yaml` candidate activities."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import yaml

from model_wtf.compliance.check import run_check
from model_wtf.compliance.exit_codes import ExitCode
from model_wtf.compliance.report import Severity
from model_wtf.extractors.clustering import (
    app_of,
    read_human_members,
    write_clusters,
)
from model_wtf.extractors.django import load_surface_file
from model_wtf.extractors.surface import SCHEMA_ID, Entrypoint, parse_surface
from model_wtf.extractors.writer import write_surface

if TYPE_CHECKING:
    from conftest import MakeRepo

SURFACE = Path(__file__).parent / "eval" / "surfaces" / "template-api.surface.json"
SNOW = "images:\n  - id: api\n    context: api\n    compliance: compliance\n"


def _gen(folder: Path, name: str) -> dict[str, object]:
    return yaml.safe_load((folder / "processing" / f"{name}.gen.yaml").read_text())


def test_app_of_precedence() -> None:
    assert (
        app_of(
            Entrypoint(id="x", path="/h/", tags=["health"], view="apps.people.api.x")
        )
        == "health"
    )
    assert (
        app_of(
            Entrypoint(id="x", path="/p/", tags=["cms-preview"], view="apps.cms.api.p")
        )
        == "cms"
    )
    assert (
        app_of(Entrypoint(id="x", path="/", view="apps.people.api.login")) == "people"
    )
    assert app_of(Entrypoint(id="x", path="/", view="billing.views.pay")) == "billing"
    assert app_of(Entrypoint(id="x", path="/", namespace="shop:cart")) == "shop"
    assert (
        app_of(Entrypoint(id="http:GET:/back/api/orders/", path="/back/api/orders/"))
        == "orders"
    )


def test_default_clusters_from_template_surface(make_repo: MakeRepo) -> None:
    root = make_repo(snow=SNOW, dirs=("api/compliance",))
    folder = root / "api/compliance"
    surface = load_surface_file(SURFACE)
    write_surface(folder, surface)

    report = write_clusters(folder, surface)

    assert report.uncovered == []
    assert sorted(p.name for p in report.written) == [
        "cms.gen.yaml",
        "health.gen.yaml",
        "people.gen.yaml",
    ]
    people = _gen(folder, "people")
    assert people["members"] == [
        "http:GET:/back/api/me/",
        "http:POST:/back/api/auth/login/",
        "http:POST:/back/api/auth/logout/",
        "task:people.tasks.purge_inactive",
    ]
    assert people["data_objects"] == {"people.user": ["read", "write"]}
    cms = _gen(folder, "cms")
    assert cms["members"] == [
        "http:GET:/back/api/pages/",
        "http:GET:/back/api/preview/",
    ]
    assert cms["data_objects"] == {"cms.homepage": ["read"]}
    assert (
        "digitalocean-spaces" not in cms["suggested_recipients"]
    )  # settings.py egress, no app
    health = _gen(folder, "health")
    assert health["members"] == ["http:GET:/back/health/"]
    assert health["data_objects"] == {}
    for text in ((folder / "processing" / n).read_text() for n in ("people.gen.yaml",)):
        assert text.startswith(
            "# GENERATED by model-wtf \u2014 do not edit; edit people.yaml"
        )

    # Idempotent.
    before = {p: p.read_text() for p in (folder / "processing").glob("*.gen.yaml")}
    write_clusters(folder, surface)
    assert {
        p: p.read_text() for p in (folder / "processing").glob("*.gen.yaml")
    } == before


def test_egress_attributed_by_provenance_folder(make_repo: MakeRepo) -> None:
    root = make_repo(snow=SNOW, dirs=("api/compliance",))
    surface = parse_surface(
        {
            "schema": SCHEMA_ID,
            "unit": "api",
            "entrypoints": [
                {
                    "id": "http:POST:/pay/",
                    "path": "/pay/",
                    "view": "apps.billing.api.pay",
                    "provenance": "apps/billing/api.py:10",
                }
            ],
            "egress": [
                {"id": "egress:sdk:stripe", "provenance": ["apps/billing/api.py:3"]}
            ],
        }
    )
    write_clusters(root / "api/compliance", surface)
    billing = _gen(root / "api/compliance", "billing")
    assert billing["egress"] == ["stripe"]
    assert billing["suggested_recipients"] == ["stripe"]


def test_related_activities_when_model_is_shared(make_repo: MakeRepo) -> None:
    root = make_repo(snow=SNOW, dirs=("api/compliance",))
    surface = parse_surface(
        {
            "schema": SCHEMA_ID,
            "unit": "api",
            "storage": [
                {"id": "store:people.User", "app_label": "people", "model": "User"}
            ],
            "entrypoints": [
                {
                    "id": "http:GET:/me/",
                    "path": "/me/",
                    "view": "apps.people.api.me",
                    "models_read": ["store:people.User"],
                },
                {
                    "id": "http:GET:/orders/",
                    "path": "/orders/",
                    "view": "apps.shop.api.orders",
                    "models_read": ["store:people.User"],
                },
            ],
        }
    )
    write_clusters(root / "api/compliance", surface)
    assert _gen(root / "api/compliance", "people")["related_activities"] == ["shop"]
    assert _gen(root / "api/compliance", "shop")["related_activities"] == ["people"]


# ---------------------------------------------------------------------------
# Human overrides
# ---------------------------------------------------------------------------


def _seed(make_repo: MakeRepo) -> tuple[Path, object]:
    root = make_repo(snow=SNOW, dirs=("api/compliance",))
    surface = load_surface_file(SURFACE)
    write_surface(root / "api/compliance", surface)
    write_clusters(root / "api/compliance", surface)
    return root / "api/compliance", surface


def test_remove_directive_on_twin(make_repo: MakeRepo) -> None:
    folder, surface = _seed(make_repo)
    (folder / "processing" / "people.yaml").write_text(
        "purpose: Authenticate users and serve their profile.\nlawful_basis: contract\n"
        "data_subject_categories: []\nmembers:\n  remove: [http:GET:/back/api/me/]\n"
    )

    report = write_clusters(folder, surface)  # type: ignore[arg-type]

    assert "http:GET:/back/api/me/" not in _gen(folder, "people")["members"]
    assert report.uncovered == ["http:GET:/back/api/me/"]


def test_split_off_activity_claims_members(make_repo: MakeRepo) -> None:
    folder, surface = _seed(make_repo)
    (folder / "processing" / "auth.yaml").write_text(
        "purpose: Log users in and out of the platform securely.\n"
        "lawful_basis: contract\n"
        "data_subject_categories: []\n"
        "members: [http:POST:/back/api/auth/login/, http:POST:/back/api/auth/logout/]\n"
    )

    report = write_clusters(folder, surface)  # type: ignore[arg-type]

    assert report.uncovered == []
    assert _gen(folder, "people")["members"] == [
        "http:GET:/back/api/me/",
        "task:people.tasks.purge_inactive",
    ]
    auth = _gen(folder, "auth")
    assert auth["members"] == [
        "http:POST:/back/api/auth/login/",
        "http:POST:/back/api/auth/logout/",
    ]
    assert auth["human_split"] is True
    directives = read_human_members(folder)
    assert directives["auth"].explicit == frozenset(auth["members"])


def test_add_directive_moves_member(make_repo: MakeRepo) -> None:
    folder, surface = _seed(make_repo)
    (folder / "processing" / "cms.yaml").write_text(
        "purpose: Publish and preview marketing pages for everyone.\n"
        "lawful_basis: legitimate_interest\n"
        "data_subject_categories: []\nmembers:\n  add: [http:GET:/back/health/]\n"
    )

    write_clusters(folder, surface)  # type: ignore[arg-type]

    assert "http:GET:/back/health/" in _gen(folder, "cms")["members"]
    assert not (folder / "processing" / "health.gen.yaml").exists() or (
        _gen(folder, "health")["members"] == []
    )


def test_uncovered_member_becomes_a_finding(make_repo: MakeRepo) -> None:
    folder, surface = _seed(make_repo)
    root = folder.parent.parent
    (folder / "actors").mkdir(exist_ok=True)
    (folder / "actors" / "users.yaml").write_text("name: Users\n")
    (folder / "processing" / "people.yaml").write_text(
        "purpose: Authenticate users and serve their own profile data.\n"
        "lawful_basis: contract\ndata_subject_categories: [users]\n"
        "members:\n  remove: [http:GET:/back/api/me/]\n"
    )
    report = write_clusters(folder, surface)  # type: ignore[arg-type]
    (folder / "elements").mkdir(exist_ok=True)
    (folder / "elements" / "coverage.gen.yaml").write_text(
        yaml.safe_dump({"by": "extractor", "uncovered_members": report.uncovered})
    )

    check = run_check(root, strict=False)

    assert check.exit_code is ExitCode.FINDINGS
    coverage = [
        d
        for d in check.diagnostics
        if d.code == "GDPR-ACTIVITY-COVERAGE" and d.element == "activity.people"
    ]
    assert coverage
    assert coverage[0].finding_id is not None

    # Claim it back: the gate passes on the next run.
    (folder / "processing" / "me.yaml").write_text(
        "purpose: Serve the authenticated user their own profile data.\n"
        "lawful_basis: contract\ndata_subject_categories: [users]\n"
        "members: [http:GET:/back/api/me/]\n"
    )
    report = write_clusters(folder, surface)  # type: ignore[arg-type]
    (folder / "elements" / "coverage.gen.yaml").write_text(
        yaml.safe_dump({"by": "extractor", "uncovered_members": report.uncovered})
    )
    check = run_check(root, strict=False)
    people_ledger = yaml.safe_load(
        (folder / "elements" / "activity.people.yaml").read_text()
    )
    assert people_ledger["GDPR-ACTIVITY-COVERAGE"]["status"] == "ok"
    # Undeclared gen-only clusters (cms, health) still block, saying why.
    cms_ledger = yaml.safe_load((folder / "elements" / "activity.cms.yaml").read_text())
    assert list(cms_ledger) == ["GDPR-PURPOSE"]
    assert cms_ledger["GDPR-PURPOSE"]["staged_because"] == "declaration missing"
    assert check.exit_code is ExitCode.FINDINGS


def test_members_key_is_schema_valid(make_repo: MakeRepo) -> None:
    root = make_repo(
        snow=SNOW,
        files={
            "api/compliance/actors/users.yaml": "name: Users\n",
            "api/compliance/processing/a.yaml": (
                "purpose: Something specific enough to pass the purpose gate here.\n"
                "lawful_basis: contract\ndata_subject_categories: [users]\n"
                "members: {add: [x], remove: [y]}\n"
            ),
            "api/compliance/processing/b.yaml": (
                "purpose: Something specific enough to pass the purpose gate here.\n"
                "lawful_basis: contract\ndata_subject_categories: [users]\n"
                "members: [x]\n"
            ),
        },
    )
    report = run_check(root, strict=False)
    assert not any(d.severity is Severity.ERROR for d in report.diagnostics), (
        report.diagnostics
    )
