"""Turn a :class:`Surface` into the unit's ``.gen.yaml`` files.

One writer for every source of facts -- the Django extractor, the
SvelteKit extractor, the agent's ``discover`` (which is converted into a
Surface first) -- so the generated files always have the same shape and
ids whatever produced them. Output is deterministic (sorted keys, no
timestamps) and only ever touches ``*.gen.yaml``: human twins, ledgers
and findings are never read or written here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import yaml

from model_wtf.knowledge.loader import load_knowledge

if TYPE_CHECKING:
    from pathlib import Path

    from model_wtf.extractors.surface import (
        Egress,
        Entrypoint,
        Storage,
        StorageField,
        Surface,
        Task,
    )
    from model_wtf.knowledge.schemas import Egress as CatalogueEgress


def gen_header(twin: str) -> str:
    """The banner every generated file starts with."""
    return f"# GENERATED by model-wtf \u2014 do not edit; edit {twin}\n"


@dataclass(slots=True)
class WriteReport:
    """Files the writer produced (unchanged files are listed too)."""

    written: list[Path] = field(default_factory=list)
    changed: list[Path] = field(default_factory=list)


def write_surface(
    folder: Path,
    surface: Surface,
    *,
    by: str = "extractor",
    source_sha: str | None = None,
) -> WriteReport:
    """Write ``elements/unit.gen.yaml``, ``data/*.gen.yaml``, ``recipients/*.gen.yaml``.

    Parameters
    ----------
    folder
        The unit's compliance folder.
    surface
        Facts about the unit.
    by
        ``extractor`` or ``agent`` -- who produced the facts.
    source_sha
        Hash of the unit's source, so ``auto`` can skip re-discovery when
        nothing changed.
    """
    report = WriteReport()
    catalogue = load_knowledge().egress

    unit: dict[str, Any] = {
        "by": by,
        "stack": sorted(surface.stack),
        "entrypoints": [
            _entrypoint(e) for e in sorted(surface.entrypoints, key=lambda e: e.id)
        ],
        "tasks": [_task(t) for t in sorted(surface.tasks, key=lambda t: t.id)],
        "config": [
            c.model_dump(mode="json", exclude_none=True)
            for c in sorted(surface.config, key=lambda c: c.key)
        ],
        "controls": dict(sorted(surface.controls.items())),
    }
    if source_sha is not None:
        unit["source_sha"] = source_sha
    _write(folder / "elements" / "unit.gen.yaml", unit, "(no twin: unit facts)", report)

    for storage in surface.storage:
        object_id = data_object_id(storage)
        _write(
            folder / "data" / f"{object_id}.gen.yaml",
            _data_object(storage, by),
            f"{object_id}.yaml",
            report,
        )

    for egress in surface.egress:
        slug = egress_slug(egress, catalogue)
        _write(
            folder / "recipients" / f"{slug}.gen.yaml",
            _recipient(egress, slug, catalogue.get(slug), surface.unit, by),
            f"{slug}.yaml",
            report,
        )
    return report


# ---------------------------------------------------------------------------
# Ids
# ---------------------------------------------------------------------------


def data_object_id(storage: Storage) -> str:
    """``store:people.User`` -> ``people.user`` (data object id = file name)."""
    return f"{storage.app_label}.{storage.model}".lower()


def egress_slug(egress: Egress, catalogue: dict[str, CatalogueEgress]) -> str:
    """Catalogue slug when the egress matches an entry, else a derived one.

    Matching is by SDK package (``egress:sdk:sentry_sdk``), host
    (``egress:host:o123.ingest.sentry.io``: any catalogue host that is a
    suffix) or credential env key.
    """
    kind, _, value = egress.id.partition(":")[2].partition(":")
    value_norm = value.lower().replace("_", "-")
    for slug, entry in catalogue.items():
        packages = {p.lower().replace("_", "-") for p in entry.detection.packages}
        if kind == "sdk" and value_norm in packages:
            return slug
        if kind == "host" and any(
            value.lower() == h.lower() or value.lower().endswith("." + h.lower())
            for h in entry.detection.hosts
        ):
            return slug
        if set(egress.credential_keys) & set(entry.detection.env):
            return slug
    if kind == "host":
        parts = value.lower().split(".")
        base = parts[-2] if len(parts) >= 2 else parts[0]
        return base.replace("_", "-")
    return value_norm or "unknown"


# ---------------------------------------------------------------------------
# Payloads
# ---------------------------------------------------------------------------


def _entrypoint(entry: Entrypoint) -> dict[str, Any]:
    data: dict[str, Any] = entry.model_dump(
        mode="json", exclude_none=True, exclude_defaults=True
    )
    data.update({"id": entry.id, "path": entry.path})
    return data


def _task(task: Task) -> dict[str, Any]:
    data: dict[str, Any] = task.model_dump(
        mode="json", exclude_none=True, exclude_defaults=True
    )
    data["id"] = task.id
    return data


def _field(f: StorageField) -> tuple[dict[str, Any], bool]:
    """One field's ``.gen`` spec and whether it smells of personal data."""
    spec: dict[str, Any] = {"type": f.type}
    pii = False
    if f.pii_hints:
        order = ("low", "medium", "high")
        best = max(f.pii_hints, key=lambda h: order.index(h.confidence))
        spec["suggested"] = best.item
        spec["confidence"] = best.confidence
        pii = best.item != "none"
    if f.opaque:
        spec["opaque"] = True
        pii = True  # unknown contents are a PII risk until classified
    if f.candidate_contents:
        spec["candidate_contents"] = sorted({c.name for c in f.candidate_contents})
    if f.fk_target:
        spec["fk_target"] = f.fk_target
        if f.on_delete:
            spec["on_delete"] = f.on_delete
    for flag in ("null", "unique", "primary_key"):
        if getattr(f, flag):
            spec[flag] = True
    spec.update(
        {k: v for k, v in (f.model_extra or {}).items() if v not in (None, [], {})}
    )
    return spec, pii


def _data_object(storage: Storage, by: str) -> dict[str, Any]:
    fields: dict[str, Any] = {}
    pii = False
    for f in storage.fields:
        fields[f.name], field_pii = _field(f)
        pii = pii or field_pii
    data: dict[str, Any] = {
        "by": by,
        "sources": [storage.id],
        "fields": fields,
        "lifecycle": storage.lifecycle.model_dump(
            mode="json", exclude_none=True, exclude_defaults=True
        ),
        "pii_suspected": pii,
    }
    if storage.shadow_store:
        data["shadow_store"] = True
    if storage.database:
        data["database"] = storage.database
    if storage.provenance:
        data["provenance"] = storage.provenance
    return data


def _recipient(
    egress: Egress, slug: str, entry: CatalogueEgress | None, unit: str, by: str
) -> dict[str, Any]:
    kind, _, value = egress.id.partition(":")[2].partition(":")
    detection: dict[str, Any] = {
        "packages": [],
        "hosts": [],
        "env": sorted(egress.credential_keys),
    }
    if kind == "sdk":
        detection["packages"] = [value]
    elif kind == "host":
        detection["hosts"] = [value]
    data: dict[str, Any] = {
        "by": by,
        "detection": detection,
        "units": [unit],
        "provenance": sorted(egress.provenance),
    }
    if egress.facts:
        data["facts"] = dict(sorted(egress.facts.items()))
    if entry is not None:
        data["suggested"] = {
            "name": entry.name,
            "kind": entry.kind,
            **(
                {"third_country": entry.default_third_country}
                if entry.default_third_country
                else {}
            ),
            **({"sink": True} if entry.sink else {}),
        }
    return data


def _write(path: Path, data: dict[str, Any], twin: str, report: WriteReport) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = gen_header(twin) + yaml.safe_dump(
        data, sort_keys=True, allow_unicode=True, width=100
    )
    if not path.is_file() or path.read_text(encoding="utf-8") != text:
        path.write_text(text, encoding="utf-8")
        report.changed.append(path)
    report.written.append(path)
